from io import StringIO
from pathlib import Path
from os import PathLike
from typing import Dict, Optional, List
from configparser import ConfigParser
from pprint import pprint as pp
from abc import ABC, abstractmethod
import json
import subprocess
import signal
import logging
import asyncio


class KlippyHost(object):

    def __init__(self, klippy_host="~/klipper/klippy/klippy.sh", config_filename="klippy-bosun.cfg", save_provider="json:saved.json"):
        self.kc = KlippyConfig(config_filename, save_provider)
        self._running: bool = False
        self._proc = None

    def register_hooks(self, register_fn):
        def startup_hook():
            logging.warning("Starting up module - klippy host management")
        register_fn("bosun:system_startup", startup_hook)
        def job_hook(register_fn):
            register_fn(self.run)
        register_fn("bosun:register_jobs", job_hook)

    @classmethod
    def configure(cls, _):
        return cls()

    def setup_env(self):
        self.kc.included_paths.append("printer.cfg")

        self.kc.generate_config_file()

    async def run(self):
        self.setup_env()
        logging.info("Starting Klippy")
        self._proc = await asyncio.create_subprocess_exec(*self.kc.process_config.full_args())
        self._running = True
        try:
            await self._proc.wait()
        except KeyboardInterrupt:
            await self._proc.send_signal(signal.SIGINT)
            await self._proc.wait()
        logging.info("Klippy termianted")
        self._proc = None
        self._running = False
        self.kc.store_saved_config()

    def start(self):
        self.setup_env()
        proc_args = self.kc.process_config.full_args()
        pp(proc_args)
        self._proc = subprocess.Popen(proc_args)
        self._ruinning = True

    def handle_stop(self):
        self._running = False
        self._proc = None
        self.kc.store_saved_config()

    def get_proc(self):
        return self._proc


class KlippySavedConfigProvider(ABC):

    @classmethod
    @abstractmethod
    def configure(spec: str) -> 'KlippySavedConfigProvider':
        pass

    @abstractmethod
    def store_config(config: Dict) -> None:
        pass
    
    @abstractmethod
    def retrieve_config() -> Dict:
        pass


class DummySavedConfigProvider(KlippySavedConfigProvider):
    @classmethod
    def configure(cls, _: str) -> 'DummySavedConfigProvider':
        return cls()

    def store_config(_, config: Dict) -> None:
        pass

    def retrieve_config(_) -> Dict:
        return {
            "hi there": {
                "nice to": "meet you",
                "what is": "your name"
            }
        }

class JsonSavedConfigProvider(KlippySavedConfigProvider):
    @classmethod
    def configure(cls, filename: str) -> 'JsonSavedConfigProvider':
        return cls(filename)

    def __init__(self, filename: str):
        self.__filepath = Path(filename)

    def retrieve_config(self) -> Dict:
        if self.__filepath.exists():
            with self.__filepath.open() as input_file:
                return dict(json.load(input_file))
        else:
            return {}

    def store_config(self, data: Dict) -> None:
        with self.__filepath.open("w+") as out_file:
            json.dump(data, out_file, indent=4)


class KlippyConfig(object):
    BANNER = \
        "# This configuration file was generated by Bosun\n" \
        "# Changes made here will be overwritten\n" \
        "# Printer configuration should go into files included here\n" \
        "# If you need to remove a saved config entry, you may do so below, and the changes will be automatically saved\n\n"

    SAVED_HEADER = \
        "#!# This SAVE_CONFIG block is managed by Bosun\n" \
        "#*# <---------------------- SAVE_CONFIG ---------------------->\n" \
        "#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.\n" \
        "#*#\n"

    def __init__(self, base_filename, saved_config_spec):
        self.process_config = KlippyHostProcessConfig()
        self.base_config_entries: Dict[str, Dict[str, str]] = {}
        self.override_config_entries: Dict[str, Dict[str, str]] = {}
        self.included_paths: List[str] = []
        self._filename = base_filename
        self._saved_config_provider = self.get_saved_config_provider(saved_config_spec)
        self.process_config.config_path = base_filename


    @staticmethod
    def get_saved_config_provider(spec):
        spec_segments = spec.split(":", 1)
        spec_class = spec_segments[0].title() + "SavedConfigProvider"
        if len(spec_segments) < 2:
            args = ""
        else:
            args = spec_segments[1]
        return globals()[spec_class].configure(args)
            
    def dict_to_config_stream(self, data, out_stream) -> None:
        temp_parser = ConfigParser()
        temp_parser.read_dict(data)
        temp_parser.write(out_stream)

    def dict_to_config(self, data) -> str:
        sio = StringIO()
        self.dict_to_config_stream(data, sio)
        return sio.getvalue()

    def dict_to_saveconfig(self, data):
        saved_config = self.dict_to_config(data)
        sio = StringIO()
        sio.write(self.SAVED_HEADER)
        for i in saved_config.splitlines():
            sio.write(f"#*# {i}\n")
        return sio.getvalue()

    def generate_config(self, out_stream):
        out_stream.write(KlippyConfig.BANNER)
        self.dict_to_config_stream(self.base_config_entries, out_stream)
        include_blocks = {f"include {s}": {} for s in self.included_paths}
        self.dict_to_config_stream(include_blocks, out_stream)
        self.dict_to_config_stream(self.override_config_entries, out_stream)
        saved_config = self.retrieve_saved_config()
        if saved_config:
            out_stream.write(self.dict_to_saveconfig(saved_config))

    def generate_config_file(self):
        with open(self._filename, "w") as conf_file:
            self.generate_config(conf_file)

    def extract_saveconfig(self, in_stream):
        sio = StringIO()
        is_in_config = False
        found_header = False
        for line in in_stream.splitlines(True):
            if not found_header:
                if line == "#*# <---------------------- SAVE_CONFIG ---------------------->\n":
                    found_header = True
                    continue
                else:
                    continue
            if not is_in_config:
                # Config begins after a blank config-prefixed line
                if line == "#*#\n":
                    is_in_config = True
                    continue
                else:
                    continue
            # At this point, we are in a config line
            if line[:4] == "#*# ":
                sio.write(line[4:])
                continue
            elif line == "#*#\n":
                sio.write(line)
                continue
            else:
                break
        temp_parser = ConfigParser()
        temp_parser.read_string(sio.getvalue())
        return {s:{k:temp_parser[s][k] for k in temp_parser[s].keys()} for s in temp_parser.sections()}

    def store_saved_config(self):
        with open(self._filename) as in_config:
            self._saved_config_provider.store_config(self.extract_saveconfig(in_config.read()))

    def retrieve_saved_config(self):
        return self._saved_config_provider.retrieve_config()



class KlippyHostProcessConfig(object):
    """
    Represents the configuration of a klippy host
    """

    def __init__(self):
        self.interperter_path: Optional[PathLike] = None
        self.klippy_path: Optional[PathLike] = None
        self.venv_path: Optional[PathLike] = None
        self.config_path: Optional[PathLike] = None
        self.input_tty_path: Optional[PathLike] = None
        self.api_socket_path: Optional[PathLike] = None
        self.log_path: Optional[PathLike] = None
        self.verbose: bool = False

        self.extra_args: List[str] = []

    def validate(self):
        if not self.config_path:
            raise ValueError("Printer configuration path was unspecified")
        if not self.klippy_path:
            raise ValueError("Klipper binary path not specified")

    def find_interp(self):
        if self.interperter_path:
            return Path(self.interperter_path).absolute()
        if self.venv_path:
            return (Path(self.venv_path) / 'bin' / 'python3').absolute()
        return "python3"

    def klippy_args(self):
        startup_args = []

        if self.input_tty_path:
            startup_args += ['-I', self.input_tty_path]

        if self.api_socket_path:
            startup_args += ['-a', self.api_socket_path]

        if self.log_path:
            startup_args += ['-l', self.log_path]

        if self.verbose:
            startup_args.append('-v')

        if self.config_path:
            startup_args.append(self.config_path)

        if self.extra_args:
            startup_args += self.extra_args

        return startup_args

    def full_args(self):
        self.validate()
        return [ str(self.find_interp()), str(self.klippy_path) ] + self.klippy_args()

# vim: set sts=4 sw=4 ts=4 et: 
